name: Auto-Format & Build on Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'release/**'

jobs:
  format_and_build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort build

      - name: Auto-format code
        run: |
          black .
          isort .

      - name: Build package
        run: python -m build
